name: ðŸš€ Release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Kind of increment (optional)
        options:
          - ''
          - MAJOR
          - MINOR
          - PATCH
        default: ''
        required: false

jobs:
  release:
    name: Bump version and create changelog with commitizen
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump using commitizen
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          changelog_increment_filename: body.md
          extra_requirements: emotional
          increment: ${{ github.event.inputs.increment }}
          debug: true

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          ref: ${{ env.REVISION }}
          github_token: ${{ github.token }}
          workflow_file_name: ci.yml
          trigger_workflow: true
          wait_workflow: true

      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
